### PR TITLE
Fix a bug that could crash program if input data contains invalid dynamic Huffman codes

### LINKED ISSUE #64: Panic in `bug` when parsing malformed file
```rust
#[test]
fn test_bug() {
    let input = b"\x04\x04\x04\x05:\x1az*\xfc\x06\x01\x90\x01\x06\x01";
    let mut decoder = Decoder::new(&input[..]);
                                                                        
    let result = io::copy(&mut decoder, &mut io::sink());
}
```

```rust
thread 'deflate::decode::tests::test_bug' panicked at 'bug', src/huffman.rs:124:43
```

### PR DESCRIPTION
**Pull request by sile**
Fixes #64

### CODE REVIEW

File: src/huffman.rs [hunk 1]
```diff
@@ -121,7 +121,7 @@ impl Builder for DecoderBuilder {
             table: self.table,
             safely_peek_bitwidth: std::cmp::min(
                 self.max_bitwidth,
-                self.safely_peek_bitwidth.expect("bug"),
+                self.safely_peek_bitwidth.unwrap_or(1),
```
Comment (sile) [inline src/huffman.rs:124]: Set the minimum bitwidth if `safely_peek_bitwidth` is `None` (this could be `None` when the input doesn't contain the EOB symbol).
